services:

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cdcdemo}
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 4L6g3nShT-eMCtK7X86sw==
    volumes:
      - ./data/kafka:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.1
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: backward
    depends_on:
      - kafka

  kafka-connect:
    build:
      context: ./kafka-connect
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: cdcraft
      CONFIG_STORAGE_TOPIC: _connect_configs
      OFFSET_STORAGE_TOPIC: _connect_offsets
      STATUS_STORAGE_TOPIC: _connect_statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      - kafka
      - schema-registry

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
        schemaRegistry:
          enabled: true
          urls:
            - http://schema-registry:8081
        kafkaConnect:
          enabled: true
          clusters:
            - name: de_mentorship
              url: http://kafka-connect:8083
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - schema-registry

  seaweed-master:
    image: chrislusf/seaweedfs
    container_name: seaweed-master
    command: 'master -ip=seaweed-master -ip.bind=0.0.0.0'
    volumes:
      - ./data/seaweed/master:/data

  seaweed-volume:
    image: chrislusf/seaweedfs
    container_name: seaweed-volume
    command: 'volume -mserver=seaweed-master:9333 -ip=seaweed-volume -ip.bind=0.0.0.0 -port=8080 -dir=/data'
    volumes:
      - ./data/seaweed/volume:/data
    depends_on:
      - seaweed-master

  seaweed-filer:
    image: chrislusf/seaweedfs
    container_name: seaweed-filer
    command: 'filer -master=seaweed-master:9333 -ip=seaweed-filer -ip.bind=0.0.0.0'
    volumes:
      - ./data/seaweed/filer:/data
    ports:
      - "8888:8888"
    depends_on:
      - seaweed-master
      - seaweed-volume

  seaweed-s3:
    image: chrislusf/seaweedfs
    container_name: seaweed-s3
    ports:
      - "8333:8333"
    command: 's3 -filer=seaweed-filer:8888 -ip.bind=0.0.0.0 -config=/etc/seaweedfs/s3-config.json'
    volumes:
      - ./seaweed/s3-config.json:/etc/seaweedfs/s3-config.json:ro
    depends_on:
      - seaweed-master
      - seaweed-volume
      - seaweed-filer

  sftp:
    image: atmoz/sftp
    container_name: sftp
    ports:
      - "2222:22"
    volumes:
      - ./data/sftp/upload:/home/naijapaveclearwatchdata/upload
    command: naijapaveclearwatchdata:pass:1001:1001:upload
