services:
  postgres:
    image: postgres:18
    container_name: de_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-de_mentorship}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql

  sftp:
    image: atmoz/sftp
    volumes:
      - ./volumes/sftp/upload:/home/naijapaveclearwatchdata/upload
    ports:
      - "2222:22"
    command: naijapaveclearwatchdata:pass:1001:1001:upload
